### ISSUE TITLE
Display output of last working version

### ISSUE THREAD

**Issue by AnubhavKhanna07** [p4p-live-remix/Remix#23]
When an erroneous piece of code is written into the commands area, currently the output in the graphical area and the terminal both disappear. Change it such that the output shown in those two areas corresponds to the immediately preceding working code version (this can be different from the versions which the "versions feature" stores because it currently only creates versions when at least 5 lines have changed).

**Comment by AnubhavKhanna07** [comment]
aka When incomplete code entered the console and graphics area show show output of last valid state

**Comment by OverCry** [comment]
Add an indicator (such as a coloured square) to represent if the current output is valid
